### ISSUE TITLE
Comparison Analysis: Speed Test Results for Image CDN Usage and Optimization

### ISSUE THREAD

**Issue by SeungJL** [AboutClan/About#152]
https://github.com/AboutClan/About/pull/149

nextJS의 이미지 최적화를 끄고, cloudfront에서 바로 이미지를 가져온다는 내용

------------------------------------------------------------------------------------------------
여러 상황을 비교해 봤어요.

일단 NEXTJS IMAGE를 사용하면서 가져오는 주소만 바꿨을 때,
![image](https://github.com/AboutClan/About/assets/84257439/407f3bac-51aa-463c-90ee-7c31d67feadb)

결국 next 서버를 거치다보니 미세하게 cloudfront가 더 느림

nextjs의 이미지 최적화 vs 최적화 끄고 cloudfront로 가져오기

![image](https://github.com/AboutClan/About/assets/84257439/0a26a3b3-03d3-46a1-bd4a-393f1d3e6a5a)
![image](https://github.com/AboutClan/About/assets/84257439/7699c42f-ffbf-4aec-8ca2-b1cd168c571c)
![image](https://github.com/AboutClan/About/assets/84257439/8dc4b21e-0103-4b25-8455-bba38443af5c)

 
webp 파일임에도 기존 next image가 더 빨리 가져오고 있음

그래서 일단은 사용을 보류함

![image](https://github.com/AboutClan/About/assets/84257439/62c04489-9bd0-4b1b-abc6-ff8815f1f97d)

그런데 조금 이상한건 위에 말한것들은 캐싱을 사용하지 않았을때임. 캐싱을 사용하면 이렇게 되는데, cloud front만 캐싱이 엄청나게 빨라짐.

그래서 s3의 메타데이터에서 캐싱을 따로 설정할 수 있는데 이것 때문에 기존 이미지 로딩이 느린가? 싶어서 관련된 문제인가도 찾아봄

적용해봤지만 딱히 크게 달리지는건 없어서 잘 모르겠음 근데

**Comment by ojj1123** [comment]
#149 PR을 닫았습니다
